language: cpp

matrix:
  include:

    - os: osx
      compiler: clang
      name: macOS
      env:
        - MATRIX_EVAL="brew update && brew install opencv@2"

    - os: linux
      compiler: clang
      name: ubuntu - clang
      addons:
        apt:
          update: true
          packages:
            - libopencv-dev
      env:
        - MATRIX_EVAL=""

    - os: linux
      compiler: gcc
      name: ubuntu - gcc
      addons:
        apt:
          update: true
          packages:
            - libopencv-dev
      env:
        - MATRIX_EVAL=""

before_install:
  - travis_retry eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Release"

script:
  - cmake --build . --target install
