# Look for the header file.
FIND_PATH(PTHREADS_INCLUDE_DIR NAMES pthread.h)

# Look for the library.
FIND_LIBRARY(PTHREADS_LIBRARY NAMES pthread pthreads pthreadsVC2)

# Handle the QUIETLY and REQUIRED arguments and set SQLITE3_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PTHREADS DEFAULT_MSG PTHREADS_LIBRARY PTHREADS_INCLUDE_DIR)

# Copy the results to the output variables.
IF(PTHREADS_FOUND)
	SET(PTHREADS_LIBRARIES ${PTHREADS_LIBRARY})
	SET(PTHREADS_INCLUDE_DIRS ${PTHREADS_INCLUDE_DIR})
ELSE()
	SET(PTHREADS_LIBRARIES)
	SET(PTHREADS_INCLUDE_DIRS)
ENDIF()

MARK_AS_ADVANCED(PTHREADS_INCLUDE_DIRS PTHREADS_LIBRARIES)
